# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{has_normalized_sti}
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Kevin Glowacz}]
  s.date = %q{2011-09-20}
  s.description = %q{      has_normalzied_sti is a rails extension to allow Single Table Inheritance
      to work with a database normalized type column.
      The extension expects the STI model to have a type_id column instead of
      a type column. type_id should reference a Types table containg all the possible types.
      The types table will be auto populated with new types as new
      subclasses are saved.
}
  s.email = %q{kevin@glowacz.info}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "README",
    "Rakefile",
    "VERSION",
    "has_normalized_sti.gemspec",
    "init.rb",
    "lib/has_normalized_sti.rb",
    "spec/has_normalized_sti_spec.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb",
    "spec/speed_test.rb"
  ]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{allows rails STI to work when the type is normalized out}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 3.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<i18n>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 3.0.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<i18n>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 3.0.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<i18n>, [">= 0"])
  end
end

